package com.montakte.app;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import java.util.HashMap;
import java.util.Map;

public class BotActivity extends Activity {
 private FirebaseFirestore db; private FirebaseUser user; private LinearLayout list;
 @Override protected void onCreate(Bundle b){super.onCreate(b);db=FirebaseFirestore.getInstance();user=FirebaseAuth.getInstance().getCurrentUser();if(user==null){finish();return;}showBots();}
 private TextView text(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.BLACK);v.setPadding(10,10,10,10);return v;}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);return b;}
 private void showBots(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);TextView title=text("🤖 Мои боты",28);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER);root.addView(title);Button catalog=button("🌐 Каталог ботов");root.addView(catalog);catalog.setOnClickListener(v->startActivity(new android.content.Intent(this,BotCatalogActivity.class)));Button create=button("＋ Создать бота");root.addView(create);create.setOnClickListener(v->createBot());ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button back=button("← Назад");root.addView(back);back.setOnClickListener(v->finish());setContentView(root);loadBots();}
 private void loadBots(){db.collection("bots").whereEqualTo("ownerUid",user.getUid()).orderBy("createdAt",Query.Direction.DESCENDING).get().addOnSuccessListener(s->{list.removeAllViews();if(s.isEmpty()){list.addView(text("Ботов пока нет. Создай первого!",18));return;}for(DocumentSnapshot d:s.getDocuments()){String n=d.getString("name"),desc=d.getString("description");TextView info=text("🤖 "+(n==null?"Без имени":n)+(desc==null||desc.isEmpty()?"":"\n"+desc),18);list.addView(info);LinearLayout row=new LinearLayout(this);Button chat=button("💬 Чат"),commands=button("⚙ Команды");row.addView(chat,new LinearLayout.LayoutParams(0,-2,1));row.addView(commands,new LinearLayout.LayoutParams(0,-2,1));list.addView(row);chat.setOnClickListener(v->{android.content.Intent i=new android.content.Intent(this,BotChatActivity.class);i.putExtra("botId",d.getId());startActivity(i);});commands.setOnClickListener(v->commands(d.getId(),n));}}).addOnFailureListener(e->Toast.makeText(this,"Не удалось загрузить ботов",Toast.LENGTH_SHORT).show());}
 private void createBot(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);root.addView(text("Создать бота 🤖",25));EditText name=new EditText(this);name.setHint("Имя бота");root.addView(name);EditText desc=new EditText(this);desc.setHint("Описание");desc.setMinLines(3);root.addView(desc);Button save=button("Создать");root.addView(save);Button back=button("← Назад");root.addView(back);back.setOnClickListener(v->showBots());setContentView(root);save.setOnClickListener(v->{String n=name.getText().toString().trim(),d=desc.getText().toString().trim();if(n.isEmpty()){name.setError("Введите имя");return;}Map<String,Object> bot=new HashMap<>();bot.put("name",n);bot.put("description",d);bot.put("ownerUid",user.getUid());bot.put("createdAt",FieldValue.serverTimestamp());bot.put("enabled",true);db.collection("bots").add(bot).addOnSuccessListener(x->{Toast.makeText(this,"Бот создан 🤖",Toast.LENGTH_SHORT).show();showBots();}).addOnFailureListener(e->Toast.makeText(this,"Не удалось создать бота",Toast.LENGTH_SHORT).show());});}
 private void commands(String botId,String botName){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);root.addView(text("⚙ Команды: "+(botName==null?"Бот":botName),24));Button add=button("＋ Добавить команду");root.addView(add);ScrollView sc=new ScrollView(this);LinearLayout cmdList=new LinearLayout(this);cmdList.setOrientation(LinearLayout.VERTICAL);sc.addView(cmdList);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button back=button("← Назад");root.addView(back);back.setOnClickListener(v->showBots());setContentView(root);add.setOnClickListener(v->addCommand(botId));db.collection("bots").document(botId).collection("commands").orderBy("trigger").get().addOnSuccessListener(s->{if(s.isEmpty())cmdList.addView(text("Команд пока нет.",17));for(DocumentSnapshot d:s.getDocuments()){String trigger=d.getString("trigger"),reply=d.getString("reply");TextView row=text((trigger==null?"/команда":trigger)+"\n→ "+(reply==null?"":reply),17);cmdList.addView(row);LinearLayout actions=new LinearLayout(this);Button edit=button("✏ Изменить"),del=button("Удалить");actions.addView(edit,new LinearLayout.LayoutParams(0,-2,1));actions.addView(del,new LinearLayout.LayoutParams(0,-2,1));cmdList.addView(actions);edit.setOnClickListener(v->editCommand(botId,d.getId(),trigger,reply));del.setOnClickListener(v->d.getReference().delete().addOnSuccessListener(x->commands(botId,botName)));}});}
 private void addCommand(String botId){editCommand(botId,null,"/","",true);}
 private void editCommand(String botId,String commandId,String oldTrigger,String oldReply){editCommand(botId,commandId,oldTrigger,oldReply,false);}
 private void editCommand(String botId,String commandId,String oldTrigger,String oldReply,boolean creating){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);root.addView(text(creating?"Новая команда":"Изменить команду",25));EditText trigger=new EditText(this);trigger.setHint("Команда, например /hello");trigger.setText(creating?"":(oldTrigger==null?"":oldTrigger));root.addView(trigger);EditText reply=new EditText(this);reply.setHint("Ответ бота");reply.setMinLines(4);reply.setText(oldReply==null?"":oldReply);root.addView(reply);Button save=button(creating?"Сохранить команду":"Сохранить изменения");root.addView(save);Button back=button("← Назад");root.addView(back);back.setOnClickListener(v->showBots());setContentView(root);save.setOnClickListener(v->{String t=trigger.getText().toString().trim().toLowerCase(),r=reply.getText().toString().trim();if(!t.startsWith("/")){trigger.setError("Команда должна начинаться с /");return;}if(t.length()<2){trigger.setError("Введите команду");return;}if(r.isEmpty()){reply.setError("Введите ответ");return;}Map<String,Object> c=new HashMap<>();c.put("trigger",t);c.put("reply",r);if(creating){c.put("createdAt",FieldValue.serverTimestamp());db.collection("bots").document(botId).collection("commands").add(c).addOnSuccessListener(x->{Toast.makeText(this,"Команда сохранена ✅",Toast.LENGTH_SHORT).show();showBots();}).addOnFailureListener(e->Toast.makeText(this,"Не удалось сохранить команду",Toast.LENGTH_SHORT).show());}else{db.collection("bots").document(botId).collection("commands").document(commandId).update(c).addOnSuccessListener(x->{Toast.makeText(this,"Команда изменена ✅",Toast.LENGTH_SHORT).show();showBots();}).addOnFailureListener(e->Toast.makeText(this,"Не удалось изменить команду",Toast.LENGTH_SHORT).show());}});}
}
