package com.montakte.app;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.NonNull;
import com.google.firebase.FirebaseException;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.auth.PhoneAuthCredential;
import com.google.firebase.auth.PhoneAuthOptions;
import com.google.firebase.auth.PhoneAuthProvider;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class MainActivity extends Activity {
    private LinearLayout root;
    private FirebaseAuth auth;
    private FirebaseFirestore db;
    private String verificationId;
    private PhoneAuthProvider.ForceResendingToken resendToken;

    @Override public void onCreate(Bundle b) { super.onCreate(b); try { auth=FirebaseAuth.getInstance(); db=FirebaseFirestore.getInstance(); FirebaseUser u=auth.getCurrentUser(); if(u==null) phoneScreen(); else {ensureUser(u); home(u);} } catch(IllegalStateException e){setupScreen();} }
    private TextView txt(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.BLACK);v.setGravity(Gravity.CENTER);v.setPadding(8,10,8,10);return v;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);return b;}
    private void root(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.TOP|Gravity.CENTER_HORIZONTAL);root.setPadding(24,24,24,24);setContentView(root);}
    private void title(String s){TextView t=txt(s,30);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);}
    private void back(Runnable r){Button b=btn("← Назад");root.addView(b);b.setOnClickListener(v->r.run());}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void phoneScreen(){root();root.setGravity(Gravity.CENTER);title("Контакте");root.addView(txt("Вход или регистрация",19));EditText p=new EditText(this);p.setHint("Номер телефона, например +7...");p.setInputType(InputType.TYPE_CLASS_PHONE);p.setSingleLine();root.addView(p);Button b=btn("Получить код");root.addView(b);b.setOnClickListener(v->{String x=p.getText().toString().trim();if(x.length()<7)p.setError("Введите номер");else sendCode(x);});}
    private void sendCode(String p){toast("Отправляем код...");PhoneAuthOptions o=PhoneAuthOptions.newBuilder(auth).setPhoneNumber(p).setTimeout(60,TimeUnit.SECONDS).setActivity(this).setCallbacks(new PhoneAuthProvider.OnVerificationStateChangedCallbacks(){public void onVerificationCompleted(@NonNull PhoneAuthCredential c){signIn(c);}public void onVerificationFailed(@NonNull FirebaseException e){toast("Не удалось отправить код: "+e.getMessage());}public void onCodeSent(@NonNull String id,@NonNull PhoneAuthProvider.ForceResendingToken t){verificationId=id;resendToken=t;codeScreen(p);}}).build();PhoneAuthProvider.verifyPhoneNumber(o);}
    private void codeScreen(String p){root();root.setGravity(Gravity.CENTER);title("Подтверждение");root.addView(txt("Код отправлен на\n"+p,17));EditText c=new EditText(this);c.setHint("Код из SMS");c.setInputType(InputType.TYPE_CLASS_NUMBER);c.setSingleLine();root.addView(c);Button ok=btn("Подтвердить"),again=btn("Отправить код ещё раз");root.addView(ok);root.addView(again);ok.setOnClickListener(v->{if(c.length()<4)c.setError("Введите код");else signIn(PhoneAuthProvider.getCredential(verificationId,c.getText().toString().trim()));});again.setOnClickListener(v->sendCode(p));}
    private void signIn(PhoneAuthCredential c){auth.signInWithCredential(c).addOnCompleteListener(this,t->{if(t.isSuccessful()){FirebaseUser u=t.getResult().getUser();if(u!=null){ensureUser(u);home(u);}}else if(t.getException() instanceof FirebaseAuthInvalidCredentialsException)toast("Неверный код");else toast("Ошибка входа: "+t.getException());});}
    private void ensureUser(FirebaseUser u){if(u.getPhoneNumber()==null)return;Map<String,Object> m=new HashMap<>();m.put("uid",u.getUid());m.put("phone",u.getPhoneNumber());m.put("updatedAt",FieldValue.serverTimestamp());db.collection("users").document(u.getUid()).set(m,com.google.firebase.firestore.SetOptions.merge());}

    private void home(FirebaseUser u){root();title("Контакте");loadProfileHeader(u);Button feed=btn("📰 Лента"),f=btn("👥 Друзья"),q=btn("📨 Заявки в друзья"),m=btn("💬 Сообщения"),p=btn("👤 Профиль");root.addView(feed);root.addView(f);root.addView(q);root.addView(m);root.addView(p);feed.setOnClickListener(v->feed(u));f.setOnClickListener(v->friends(u));q.setOnClickListener(v->requests(u));m.setOnClickListener(v->messages(u));p.setOnClickListener(v->profile(u));}
    private void loadProfileHeader(FirebaseUser u){db.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{String n=d.getString("displayName"),a=d.getString("avatar");root.addView(txt((a==null?"👤":a)+" "+(n==null||n.isEmpty()?"Аккаунт":n),17),1);});}

    private void feed(FirebaseUser u){root();title("Лента");Button create=btn("＋ Создать пост");root.addView(create);create.setOnClickListener(v->createPost(u));ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));back(()->home(u));db.collection("posts").orderBy("createdAt",Query.Direction.DESCENDING).limit(50).addSnapshotListener((snap,e)->{if(e!=null||snap==null)return;list.removeAllViews();if(snap.isEmpty())list.addView(txt("Постов пока нет. Создай первый!",18));for(DocumentSnapshot d:snap.getDocuments())renderPost(d,u,list);});}
    private void renderPost(DocumentSnapshot d,FirebaseUser u,LinearLayout list){String author=d.getString("authorUid"),body=d.getString("text");Long likes=d.getLong("likeCount");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(8,16,8,16);TextView t=txt("",16);list.addView(card);db.collection("users").document(author).get().addOnSuccessListener(x->{String n=x.getString("displayName");t.setText("👤 "+(n==null||n.isEmpty()?x.getString("phone"):n));});card.addView(t);card.addView(txt(body==null?"":body,19));Button like=btn("❤️ "+(likes==null?0:likes)+"  Лайк"),comments=btn("💬 Комментарии");card.addView(like);card.addView(comments);String pid=d.getId();db.collection("posts").document(pid).collection("likes").document(u.getUid()).get().addOnSuccessListener(x->{like.setText("❤️ "+(likes==null?0:likes)+(x.exists()?"  Вы лайкнули":"  Лайк"));});like.setOnClickListener(v->toggleLike(pid,u,like,likes==null?0:likes));comments.setOnClickListener(v->comments(u,pid,body));}
    private void createPost(FirebaseUser u){root();title("Новый пост");EditText e=new EditText(this);e.setHint("Что нового?");e.setGravity(Gravity.TOP);e.setMinLines(5);root.addView(e);Button b=btn("Опубликовать");root.addView(b);back(()->feed(u));b.setOnClickListener(v->{String s=e.getText().toString().trim();if(s.isEmpty()){e.setError("Напишите текст");return;}Map<String,Object> p=new HashMap<>();p.put("authorUid",u.getUid());p.put("text",s);p.put("likeCount",0);p.put("createdAt",FieldValue.serverTimestamp());db.collection("posts").add(p).addOnSuccessListener(x->{toast("Пост опубликован");feed(u);});});}
    private void toggleLike(String pid,FirebaseUser u,Button b,long count){db.collection("posts").document(pid).collection("likes").document(u.getUid()).get().addOnSuccessListener(d->{if(d.exists()){db.collection("posts").document(pid).collection("likes").document(u.getUid()).delete().addOnSuccessListener(x->db.collection("posts").document(pid).update("likeCount",Math.max(0,count-1)));}else{Map<String,Object> x=new HashMap<>();x.put("uid",u.getUid());db.collection("posts").document(pid).collection("likes").document(u.getUid()).set(x).addOnSuccessListener(z->db.collection("posts").document(pid).update("likeCount",count+1));}});}
    private void comments(FirebaseUser u,String pid,String postText){root();title("Комментарии");root.addView(txt(postText==null?"":postText,17));ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));EditText input=new EditText(this);input.setHint("Комментарий");Button send=btn("Отправить");LinearLayout bar=new LinearLayout(this);bar.addView(input,new LinearLayout.LayoutParams(0,-2,1));bar.addView(send);root.addView(bar);back(()->feed(u));Query q=db.collection("posts").document(pid).collection("comments").orderBy("createdAt",Query.Direction.ASCENDING);q.addSnapshotListener((snap,e)->{if(e!=null||snap==null)return;list.removeAllViews();for(DocumentSnapshot d:snap.getDocuments()){String a=d.getString("authorUid"),s=d.getString("text");list.addView(txt("👤 "+a+": "+s,16));}});send.setOnClickListener(v->{String s=input.getText().toString().trim();if(s.isEmpty())return;Map<String,Object> c=new HashMap<>();c.put("authorUid",u.getUid());c.put("text",s);c.put("createdAt",FieldValue.serverTimestamp());db.collection("posts").document(pid).collection("comments").add(c).addOnSuccessListener(x->input.setText(""));});}

    private void friends(FirebaseUser u){root();title("Друзья");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);back(()->home(u));loadFriends(u,list);Button add=btn("＋ Добавить друга");root.addView(add);add.setOnClickListener(v->findUser(u));}
    private void loadFriends(FirebaseUser u,LinearLayout list){db.collection("friendships").whereEqualTo("userA",u.getUid()).get().addOnSuccessListener(s->renderFriends(s.getDocuments(),u,list));db.collection("friendships").whereEqualTo("userB",u.getUid()).get().addOnSuccessListener(s->renderFriends(s.getDocuments(),u,list));}
    private void renderFriends(List<DocumentSnapshot> ds,FirebaseUser u,LinearLayout list){for(DocumentSnapshot d:ds){String a=d.getString("userA"),b=d.getString("userB"),o=u.getUid().equals(a)?b:a;if(o!=null)db.collection("users").document(o).get().addOnSuccessListener(x->list.addView(txt("👤 "+(x.getString("displayName")==null?x.getString("phone"):x.getString("displayName")),18)));}}
    private void requests(FirebaseUser u){root();title("Заявки в друзья");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);back(()->home(u));db.collection("friendRequests").whereEqualTo("receiverUid",u.getUid()).whereEqualTo("status","pending").get().addOnSuccessListener(s->{if(s.isEmpty())list.addView(txt("Новых заявок нет",18));for(DocumentSnapshot d:s.getDocuments())requestRow(d,u,list);});}
    private void requestRow(DocumentSnapshot d,FirebaseUser u,LinearLayout list){String sender=d.getString("senderUid");db.collection("users").document(sender).get().addOnSuccessListener(x->{LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.addView(txt("Заявка от "+(x.getString("displayName")==null?x.getString("phone"):x.getString("displayName")),17));Button a=btn("Принять"),no=btn("Отклонить");r.addView(a);r.addView(no);list.addView(r);a.setOnClickListener(v->accept(d.getId(),sender,u));no.setOnClickListener(v->db.collection("friendRequests").document(d.getId()).update("status","rejected").addOnSuccessListener(z->requests(u)));});}
    private void accept(String id,String sender,FirebaseUser u){db.collection("friendRequests").document(id).update("status","accepted").addOnSuccessListener(v->{String key=friendshipId(sender,u.getUid());List<String> ids=new ArrayList<>(Arrays.asList(sender,u.getUid()));Collections.sort(ids);Map<String,Object> m=new HashMap<>();m.put("userA",ids.get(0));m.put("userB",ids.get(1));m.put("createdAt",FieldValue.serverTimestamp());db.collection("friendships").document(key).set(m).addOnSuccessListener(x->requests(u));});}
    private void findUser(FirebaseUser u){root();title("Добавить в друзья");EditText e=new EditText(this);e.setHint("Номер телефона");e.setInputType(InputType.TYPE_CLASS_PHONE);root.addView(e);Button b=btn("Отправить заявку");root.addView(b);back(()->friends(u));b.setOnClickListener(v->{String p=e.getText().toString().trim();db.collection("users").whereEqualTo("phone",p).limit(1).get().addOnSuccessListener(s->{if(s.isEmpty()){toast("Пользователь не найден");return;}String o=s.getDocuments().get(0).getId();if(o.equals(u.getUid())){toast("Нельзя добавить себя");return;}String id=u.getUid()+"_"+o;Map<String,Object> x=new HashMap<>();x.put("senderUid",u.getUid());x.put("receiverUid",o);x.put("status","pending");x.put("createdAt",FieldValue.serverTimestamp());db.collection("friendRequests").document(id).set(x).addOnSuccessListener(z->toast("Заявка отправлена"));});});}

    private void messages(FirebaseUser u){root();title("Сообщения");Button n=btn("＋ Новый чат");root.addView(n);n.setOnClickListener(v->newChat(u));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);back(()->home(u));db.collection("conversations").whereArrayContains("participants",u.getUid()).get().addOnSuccessListener(s->{if(s.isEmpty())list.addView(txt("Диалогов пока нет",18));for(DocumentSnapshot d:s.getDocuments()){List<String> ps=(List<String>)d.get("participants");if(ps==null)continue;for(String o:ps)if(!o.equals(u.getUid())){db.collection("users").document(o).get().addOnSuccessListener(x->{Button b=btn("💬 "+(x.getString("displayName")==null?x.getString("phone"):x.getString("displayName")));list.addView(b);b.setOnClickListener(v->chat(u,o));});break;}}});}
    private void newChat(FirebaseUser u){root();title("Новый чат");EditText e=new EditText(this);e.setHint("Телефон получателя");e.setInputType(InputType.TYPE_CLASS_PHONE);root.addView(e);Button b=btn("Открыть чат");root.addView(b);back(()->messages(u));b.setOnClickListener(v->db.collection("users").whereEqualTo("phone",e.getText().toString().trim()).limit(1).get().addOnSuccessListener(s->{if(!s.isEmpty()){String o=s.getDocuments().get(0).getId();if(!o.equals(u.getUid()))chat(u,o);}}));}
    private String friendshipId(String a,String b){List<String> x=new ArrayList<>(Arrays.asList(a,b));Collections.sort(x);return x.get(0)+"_"+x.get(1);}
    private void chat(FirebaseUser u,String o){root();title("Чат");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);EditText e=new EditText(this);e.setHint("Сообщение");Button send=btn("Отправить");bar.addView(e,new LinearLayout.LayoutParams(0,-2,1));bar.addView(send);root.addView(bar);back(()->messages(u));String cid=friendshipId(u.getUid(),o);Map<String,Object> c=new HashMap<>();c.put("participants",Arrays.asList(u.getUid(),o));db.collection("conversations").document(cid).set(c,com.google.firebase.firestore.SetOptions.merge());db.collection("conversations").document(cid).collection("messages").orderBy("createdAt",Query.Direction.ASCENDING).addSnapshotListener((s,err)->{if(err!=null||s==null)return;list.removeAllViews();for(DocumentSnapshot d:s.getDocuments())list.addView(txt((u.getUid().equals(d.getString("senderUid"))?"Вы: ":"Собеседник: ")+d.getString("text"),17));});send.setOnClickListener(v->{String x=e.getText().toString().trim();if(x.isEmpty())return;Map<String,Object> m=new HashMap<>();m.put("senderUid",u.getUid());m.put("text",x);m.put("createdAt",FieldValue.serverTimestamp());db.collection("conversations").document(cid).collection("messages").add(m).addOnSuccessListener(z->e.setText(""));});}

    private void profile(FirebaseUser u){root();title("Профиль");TextView info=txt("Загрузка...",17);root.addView(info);EditText name=new EditText(this);name.setHint("Имя");root.addView(name);Button save=btn("Сохранить имя и аватар");root.addView(save);TextView avatars=txt("Выбери аватар: 👤  😎  🐱  🚀  ⭐",18);root.addView(avatars);Button a1=btn("👤"),a2=btn("😎"),a3=btn("🐱"),a4=btn("🚀"),a5=btn("⭐");root.addView(a1);root.addView(a2);root.addView(a3);root.addView(a4);root.addView(a5);final String[] av={"👤"};a1.setOnClickListener(v->av[0]="👤");a2.setOnClickListener(v->av[0]="😎");a3.setOnClickListener(v->av[0]="🐱");a4.setOnClickListener(v->av[0]="🚀");a5.setOnClickListener(v->av[0]="⭐");db.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{String n=d.getString("displayName"),x=d.getString("avatar");if(n!=null)name.setText(n);info.setText((x==null?"👤":x)+"  "+(n==null?"":n)+"\n"+(u.getPhoneNumber()==null?"":u.getPhoneNumber()));});save.setOnClickListener(v->{Map<String,Object> m=new HashMap<>();m.put("displayName",name.getText().toString().trim());m.put("avatar",av[0]);db.collection("users").document(u.getUid()).set(m,com.google.firebase.firestore.SetOptions.merge()).addOnSuccessListener(x->{toast("Профиль сохранён");home(u);});});back(()->home(u));}
    private void setupScreen(){root();root.setGravity(Gravity.CENTER);title("Контакте");root.addView(txt("Нужно подключить Firebase-проект и google-services.json.",18));}
}
