package com.montakte.app;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.content.Intent;
import android.net.Uri;
import android.webkit.MimeTypeMap;
import android.widget.*;
import androidx.annotation.NonNull;
import com.google.firebase.FirebaseException;
import com.google.firebase.auth.*;
import com.google.firebase.firestore.*;
import com.google.firebase.storage.*;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class MainActivity extends Activity {
    private LinearLayout root, content;
    private FirebaseAuth auth; private FirebaseFirestore db; private FirebaseStorage storage;
    private String verificationId; private PhoneAuthProvider.ForceResendingToken resendToken;
    private static final int PICK_MEDIA=901; private Uri selectedMedia;
    private final String accent="#2684FF";

    @Override public void onCreate(Bundle b){super.onCreate(b);try{auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();storage=FirebaseStorage.getInstance();FirebaseUser u=auth.getCurrentUser();if(u==null)phoneScreen();else checkProfile(u);}catch(Exception e){phoneScreen();}}
    private GradientDrawable bg(String c,float r){GradientDrawable g=new GradientDrawable();g.setColor(Color.parseColor(c));g.setCornerRadius(r);return g;}
    private TextView text(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,4,0,4);return v;}
    private TextView center(String s,float z,int c){TextView v=text(s,z,c);v.setGravity(Gravity.CENTER);return v;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(accent,28));b.setPadding(18,3,18,3);return b;}
    private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setSingleLine();e.setPadding(18,0,18,0);e.setBackground(bg("#F1F5FA",22));return e;}
    private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.parseColor("#F5F7FB"));setContentView(root);}
    private void authBase(){base();root.setGravity(Gravity.CENTER);root.setPadding(28,24,28,24);}
    private void logo(){TextView l=center("ВО",42,Color.WHITE);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.setBackground(bg(accent,32));root.addView(l,new LinearLayout.LayoutParams(104,104));}
    private void header(String t,String sub){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(20,20,20,12);TextView x=text(t,27,Color.parseColor("#14213D"));x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(x);if(sub!=null)h.addView(text(sub,14,Color.parseColor("#667085")));root.addView(h);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}

    private void phoneScreen(){authBase();logo();Space a=new Space(this);root.addView(a,new LinearLayout.LayoutParams(1,16));TextView t=center("Добро пожаловать в ВОнтакте",24,Color.parseColor("#14213D"));t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);root.addView(center("Вход и регистрация по номеру телефона",15,Color.parseColor("#667085")));Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,22));EditText phone=input("Номер телефона, например +7 900 000-00-00");phone.setInputType(InputType.TYPE_CLASS_PHONE);root.addView(phone,new LinearLayout.LayoutParams(-1,54));Space s2=new Space(this);root.addView(s2,new LinearLayout.LayoutParams(1,14));Button next=button("Продолжить");root.addView(next,new LinearLayout.LayoutParams(-1,52));root.addView(center("Мы отправим SMS-код для подтверждения номера.",13,Color.parseColor("#8A94A6")));next.setOnClickListener(v->{String p=phone.getText().toString().trim();if(p.length()<7){phone.setError("Введите номер телефона");return;}sendCode(p);});}
    private void sendCode(String p){toast("Отправляем SMS-код…");PhoneAuthOptions o=PhoneAuthOptions.newBuilder(auth).setPhoneNumber(p).setTimeout(60L,TimeUnit.SECONDS).setActivity(this).setCallbacks(new PhoneAuthProvider.OnVerificationStateChangedCallbacks(){public void onVerificationCompleted(@NonNull PhoneAuthCredential c){signIn(c);}public void onVerificationFailed(@NonNull FirebaseException e){toast("Не удалось отправить код: "+e.getMessage());}public void onCodeSent(@NonNull String id,@NonNull PhoneAuthProvider.ForceResendingToken t){verificationId=id;resendToken=t;codeScreen(p);}}).build();PhoneAuthProvider.verifyPhoneNumber(o);}
    private void codeScreen(String p){authBase();logo();Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,16));root.addView(center("Подтверждение номера",24,Color.parseColor("#14213D")));root.addView(center("Код отправлен на\n"+p,15,Color.parseColor("#667085")));Space s2=new Space(this);root.addView(s2,new LinearLayout.LayoutParams(1,20));EditText c=input("Код из SMS");c.setInputType(InputType.TYPE_CLASS_NUMBER);root.addView(c,new LinearLayout.LayoutParams(-1,54));Space s3=new Space(this);root.addView(s3,new LinearLayout.LayoutParams(1,14));Button ok=button("Войти / зарегистрироваться");root.addView(ok,new LinearLayout.LayoutParams(-1,52));Button again=new Button(this);again.setText("Отправить код ещё раз");again.setAllCaps(false);again.setTextColor(Color.parseColor(accent));again.setBackgroundColor(Color.TRANSPARENT);root.addView(again);ok.setOnClickListener(v->{if(c.length()<4){c.setError("Введите код");return;}if(verificationId==null){toast("Сначала запросите код");return;}signIn(PhoneAuthProvider.getCredential(verificationId,c.getText().toString().trim()));});again.setOnClickListener(v->sendCode(p));}
    private void signIn(PhoneAuthCredential c){auth.signInWithCredential(c).addOnCompleteListener(this,t->{if(t.isSuccessful()&&t.getResult().getUser()!=null)checkProfile(t.getResult().getUser());else if(t.getException() instanceof FirebaseAuthInvalidCredentialsException)toast("Неверный SMS-код");else toast("Ошибка входа: "+(t.getException()==null?"неизвестная ошибка":t.getException().getMessage()));});}
    private void checkProfile(FirebaseUser u){db.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{String n=d.getString("displayName");if(n==null||n.trim().isEmpty())profileSetup(u);else feed(u);}).addOnFailureListener(e->profileSetup(u));}
    private void profileSetup(FirebaseUser u){authBase();logo();Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,16));root.addView(center("Создайте профиль",25,Color.parseColor("#14213D")));root.addView(center("Остался один шаг — ваше имя",15,Color.parseColor("#667085")));Space s2=new Space(this);root.addView(s2,new LinearLayout.LayoutParams(1,20));EditText name=input("Имя и фамилия");root.addView(name,new LinearLayout.LayoutParams(-1,54));Space s3=new Space(this);root.addView(s3,new LinearLayout.LayoutParams(1,14));EditText avatar=input("Аватар, например 🦊 (необязательно)");root.addView(avatar,new LinearLayout.LayoutParams(-1,54));Space s4=new Space(this);root.addView(s4,new LinearLayout.LayoutParams(1,14));Button save=button("Создать профиль");root.addView(save,new LinearLayout.LayoutParams(-1,52));save.setOnClickListener(v->{String n=name.getText().toString().trim();if(n.length()<2){name.setError("Введите имя");return;}Map<String,Object> m=new HashMap<>();m.put("uid",u.getUid());m.put("phone",u.getPhoneNumber());m.put("displayName",n);m.put("avatar",avatar.getText().toString().trim());m.put("createdAt",FieldValue.serverTimestamp());m.put("updatedAt",FieldValue.serverTimestamp());save.setEnabled(false);db.collection("users").document(u.getUid()).set(m,SetOptions.merge()).addOnSuccessListener(x->feed(u)).addOnFailureListener(e->{save.setEnabled(true);toast("Не удалось создать профиль: "+e.getMessage());});});}

    private void feed(FirebaseUser u){base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(18,10,18,8);TextView brand=text("ВОнтакте",24,Color.parseColor("#14213D"));brand.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(brand,new LinearLayout.LayoutParams(0,58,1));Button prof=button("Профиль");top.addView(prof,new LinearLayout.LayoutParams(108,48));root.addView(top);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(14,0,14,88);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));composer(u);loadPosts(u);LinearLayout nav=new LinearLayout(this);nav.setPadding(8,4,8,6);nav.setBackgroundColor(Color.WHITE);String[] labels={"⌂\nГлавная","♙\nДрузья","✉\nСообщения","☰\nМеню"};for(String x:labels){Button b=new Button(this);b.setText(x);b.setTextSize(12);b.setAllCaps(false);b.setTextColor(Color.parseColor("#536174"));b.setBackgroundColor(Color.TRANSPARENT);nav.addView(b,new LinearLayout.LayoutParams(0,64,1));if(x.startsWith("⌂"))b.setTextColor(Color.parseColor(accent));if(x.startsWith("♙"))b.setOnClickListener(v->friends(u));if(x.startsWith("✉"))b.setOnClickListener(v->messages(u));if(x.startsWith("☰"))b.setOnClickListener(v->menu(u));}root.addView(nav);prof.setOnClickListener(v->profile(u));}
    private void composer(FirebaseUser u){LinearLayout c=card();c.addView(text("Что нового?",17,Color.parseColor("#536174")));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);Button post=button("＋ Создать пост");Button media=button("Фото/видео");media.setTextColor(Color.parseColor(accent));media.setBackground(bg("#EAF3FF",28));r.addView(post);r.addView(media,new LinearLayout.LayoutParams(-2,48));c.addView(r);content.addView(c);Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,12));post.setOnClickListener(v->createPost(u));media.setOnClickListener(v->createPost(u));}
    private void loadPosts(FirebaseUser u){TextView h=text("Лента",22,Color.parseColor("#14213D"));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);db.collection("posts").orderBy("createdAt",Query.Direction.DESCENDING).limit(50).addSnapshotListener((snap,e)->{if(e!=null||snap==null)return;while(content.getChildCount()>2)content.removeViewAt(2);if(snap.isEmpty()){LinearLayout c=card();c.addView(center("Постов пока нет",19,Color.parseColor("#14213D")));c.addView(center("Создайте первый пост — он появится здесь.",14,Color.parseColor("#667085")));content.addView(c);return;}for(DocumentSnapshot d:snap.getDocuments())renderPost(d,u);});}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,16,18,16);c.setBackground(bg("#FFFFFF",22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,12);c.setLayoutParams(p);return c;}
    private void renderPost(DocumentSnapshot d,FirebaseUser u){String author=d.getString("authorUid"),body=d.getString("text"),url=d.getString("mediaUrl"),type=d.getString("mediaType");Long likes=d.getLong("likeCount");LinearLayout c=card();TextView who=text("Загрузка профиля…",15,Color.parseColor("#536174"));who.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(who);if(author!=null)db.collection("users").document(author).get().addOnSuccessListener(x->{String n=x.getString("displayName"),a=x.getString("avatar");who.setText((a==null||a.isEmpty()?"👤":a)+"  "+(n==null||n.isEmpty()?x.getString("phone"):n));});if(body!=null&&!body.isEmpty()){TextView b=text(body,17,Color.parseColor("#14213D"));b.setPadding(0,12,0,12);c.addView(b);}if(url!=null&&!url.isEmpty()){if(type!=null&&type.startsWith("video/")){VideoView v=new VideoView(this);v.setVideoURI(Uri.parse(url));c.addView(v,new LinearLayout.LayoutParams(-1,420));Button play=button("▶ Смотреть видео");c.addView(play);play.setOnClickListener(x->v.start());}else{ImageView iv=new ImageView(this);iv.setAdjustViewBounds(true);iv.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(iv,new LinearLayout.LayoutParams(-1,420));com.bumptech.glide.Glide.with(this).load(url).into(iv);}}LinearLayout actions=new LinearLayout(this);Button like=new Button(this),comments=new Button(this);like.setAllCaps(false);comments.setAllCaps(false);like.setTextColor(Color.parseColor("#536174"));comments.setTextColor(Color.parseColor("#536174"));like.setBackgroundColor(Color.TRANSPARENT);comments.setBackgroundColor(Color.TRANSPARENT);like.setText("♡ "+(likes==null?0:likes));comments.setText("💬 Комментарии");actions.addView(like,new LinearLayout.LayoutParams(0,52,1));actions.addView(comments,new LinearLayout.LayoutParams(0,52,1));c.addView(actions);content.addView(c);String pid=d.getId();db.collection("posts").document(pid).collection("likes").document(u.getUid()).get().addOnSuccessListener(x->like.setText((x.exists()?"♥":"♡")+" "+(likes==null?0:likes)));like.setOnClickListener(v->toggleLike(pid,u));comments.setOnClickListener(v->comments(u,pid));}
    private void toggleLike(String pid,FirebaseUser u){DocumentReference p=db.collection("posts").document(pid),l=p.collection("likes").document(u.getUid());l.get().addOnSuccessListener(d->{if(d.exists())l.delete().addOnSuccessListener(x->p.update("likeCount",FieldValue.increment(-1)));else{Map<String,Object> m=new HashMap<>();m.put("uid",u.getUid());l.set(m).addOnSuccessListener(x->p.update("likeCount",FieldValue.increment(1)));}});}
    private void createPost(FirebaseUser u){base();header("Новый пост","Поделитесь с друзьями");LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(18,8,18,18);EditText body=input("Что хотите рассказать?");body.setGravity(Gravity.TOP);body.setMinLines(5);box.addView(body,new LinearLayout.LayoutParams(-1,150));TextView selected=text("Медиа не выбрано",14,Color.parseColor("#667085"));box.addView(selected);Button media=button("📎 Добавить фото или видео");box.addView(media,new LinearLayout.LayoutParams(-1,50));Button publish=button("Опубликовать");LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,52);pp.setMargins(0,12,0,0);box.addView(publish,pp);Button back=new Button(this);back.setText("Назад");back.setAllCaps(false);box.addView(back);root.addView(box);selectedMedia=null;media.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","video/*"});startActivityForResult(i,PICK_MEDIA);});back.setOnClickListener(v->feed(u));publish.setOnClickListener(v->{String s=body.getText().toString().trim();if(s.isEmpty()&&selectedMedia==null){body.setError("Добавьте текст или фото/видео");return;}publish.setEnabled(false);if(selectedMedia==null)savePost(u,s,null,null,publish);else uploadPost(u,s,publish);});}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_MEDIA&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){selectedMedia=data.getData();if(root!=null){for(int i=0;i<root.getChildCount();i++){View v=root.getChildAt(i);if(v instanceof TextView&&((TextView)v).getText().toString().equals("Медиа не выбрано")){((TextView)v).setText("✓ Медиа выбрано");break;}}}}}
    private void uploadPost(FirebaseUser u,String body,Button publish){String mime=getContentResolver().getType(selectedMedia);if(mime==null||(!mime.startsWith("image/")&&!mime.startsWith("video/"))){publish.setEnabled(true);toast("Выберите фото или видео");return;}String ext=MimeTypeMap.getSingleton().getExtensionFromMimeType(mime);if(ext==null)ext="bin";StorageReference r=storage.getReference().child("post_media").child(u.getUid()).child(UUID.randomUUID()+"."+ext);toast("Загружаем медиа…");r.putFile(selectedMedia).continueWithTask(t->{if(!t.isSuccessful()&&t.getException()!=null)throw t.getException();return r.getDownloadUrl();}).addOnSuccessListener(x->savePost(u,body,x.toString(),mime,publish)).addOnFailureListener(e->{publish.setEnabled(true);toast("Ошибка загрузки: "+e.getMessage());});}
    private void savePost(FirebaseUser u,String body,String url,String mime,Button publish){Map<String,Object> p=new HashMap<>();p.put("authorUid",u.getUid());p.put("text",body);p.put("likeCount",0);p.put("createdAt",FieldValue.serverTimestamp());if(url!=null){p.put("mediaUrl",url);p.put("mediaType",mime);}db.collection("posts").add(p).addOnSuccessListener(x->{toast("Пост опубликован ✓");feed(u);}).addOnFailureListener(e->{publish.setEnabled(true);toast("Ошибка публикации: "+e.getMessage());});}
    private void comments(FirebaseUser u,String pid){base();header("Комментарии","Обсуждение поста");ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(14,0,14,10);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);EditText in=input("Написать комментарий…");Button send=button("Отправить");bar.addView(in,new LinearLayout.LayoutParams(0,54,1));bar.addView(send,new LinearLayout.LayoutParams(120,54));root.addView(bar);Button back=new Button(this);back.setText("Назад");back.setAllCaps(false);root.addView(back);back.setOnClickListener(v->feed(u));db.collection("posts").document(pid).collection("comments").orderBy("createdAt",Query.Direction.ASCENDING).addSnapshotListener((snap,e)->{if(e!=null||snap==null)return;list.removeAllViews();for(DocumentSnapshot d:snap.getDocuments()){LinearLayout c=card();c.addView(text(d.getString("text"),15,Color.parseColor("#14213D")));list.addView(c);}});send.setOnClickListener(v->{String s=in.getText().toString().trim();if(s.isEmpty())return;Map<String,Object> c=new HashMap<>();c.put("authorUid",u.getUid());c.put("text",s);c.put("createdAt",FieldValue.serverTimestamp());db.collection("posts").document(pid).collection("comments").add(c).addOnSuccessListener(x->in.setText(""));});}
    private void profile(FirebaseUser u){base();header("Профиль","Ваш аккаунт ВОнтакте");LinearLayout c=card();TextView av=center("👤",48,Color.WHITE);av.setBackground(bg(accent,50));c.addView(av,new LinearLayout.LayoutParams(86,86));db.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{TextView n=center(d.getString("displayName"),22,Color.parseColor("#14213D"));n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(n);c.addView(center(d.getString("phone"),14,Color.parseColor("#667085")));});root.addView(c);Button out=button("Выйти");root.addView(out,new LinearLayout.LayoutParams(-1,52));Button back=new Button(this);back.setText("← В ленту");back.setAllCaps(false);root.addView(back);back.setOnClickListener(v->feed(u));out.setOnClickListener(v->{auth.signOut();phoneScreen();});}
    private void friends(FirebaseUser u){base();header("Друзья","Ваши друзья");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);db.collection("friendships").whereEqualTo("userA",u.getUid()).get().addOnSuccessListener(s->friendRows(s.getDocuments(),u,list));db.collection("friendships").whereEqualTo("userB",u.getUid()).get().addOnSuccessListener(s->friendRows(s.getDocuments(),u,list));Button back=new Button(this);back.setText("← В ленту");back.setAllCaps(false);root.addView(back);back.setOnClickListener(v->feed(u));}
    private void friendRows(List<DocumentSnapshot> ds,FirebaseUser u,LinearLayout list){for(DocumentSnapshot d:ds){String a=d.getString("userA"),b=d.getString("userB"),o=u.getUid().equals(a)?b:a;if(o!=null)db.collection("users").document(o).get().addOnSuccessListener(x->{LinearLayout c=card();c.addView(text("👤 "+(x.getString("displayName")==null?x.getString("phone"):x.getString("displayName")),17,Color.parseColor("#14213D")));list.addView(c);});}}
    private void messages(FirebaseUser u){base();header("Сообщения","Ваши диалоги");TextView e=center("Раздел сообщений подключается к диалогам.",16,Color.parseColor("#667085"));root.addView(e);Button back=new Button(this);back.setText("← В ленту");back.setAllCaps(false);root.addView(back);back.setOnClickListener(v->feed(u));}
    private void menu(FirebaseUser u){base();header("Меню","ВОнтакте");Button groups=button("👥 Группы");Button channels=button("📢 Каналы");Button bots=button("🤖 Боты");root.addView(groups,new LinearLayout.LayoutParams(-1,52));root.addView(channels,new LinearLayout.LayoutParams(-1,52));root.addView(bots,new LinearLayout.LayoutParams(-1,52));Button back=new Button(this);back.setText("← В ленту");back.setAllCaps(false);root.addView(back);groups.setOnClickListener(v->startActivity(new Intent(this,CommunitiesActivity.class).putExtra("communityType","group")));channels.setOnClickListener(v->startActivity(new Intent(this,CommunitiesActivity.class).putExtra("communityType","channel")));bots.setOnClickListener(v->startActivity(new Intent(this,BotActivity.class)));back.setOnClickListener(v->feed(u));}
}
