const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { onSchedule } = require('firebase-functions/v2/scheduler');
const { setGlobalOptions } = require('firebase-functions/v2');
const { defineSecret } = require('firebase-functions/params');
const admin = require('firebase-admin');
admin.initializeApp(); setGlobalOptions({ region: 'europe-west1' });
const OPENAI_API_KEY = defineSecret('OPENAI_API_KEY');
async function sendToUser(uid,message){const s=await admin.firestore().collection('users').doc(uid).get();const token=s.get('fcmToken');if(!token)return;try{await admin.messaging().send({token,...message});}catch(e){console.error('FCM send failed',e);}}
async function suspendUser(uid,days,reason){const until=new Date(Date.now()+days*86400000);try{await admin.auth().updateUser(uid,{disabled:true});await admin.firestore().collection('users').doc(uid).set({moderationSuspendedUntil:admin.firestore.Timestamp.fromDate(until),moderationReason:reason},{merge:true});}catch(e){console.error('Moderation suspension failed',e);}}
function buildModerationInput(data){const input=[];const text=typeof data?.text==='string'?data.text.trim():'';if(text)input.push({type:'text',text});const mediaUrl=typeof data?.mediaUrl==='string'?data.mediaUrl.trim():'';if(mediaUrl&&/^https?:\/\//i.test(mediaUrl))input.push({type:'image_url',image_url:{url:mediaUrl}});return input;}
async function containsAdultContent(data,apiKey){if(data?.adultContent===true)return true;const input=buildModerationInput(data);if(!input.length||!apiKey)return false;try{const r=await fetch('https://api.openai.com/v1/moderations',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'omni-moderation-latest',input})});if(!r.ok){console.error('Moderation API failed:',r.status,await r.text());return false;}const j=await r.json();return Boolean(j?.results?.some(x=>x?.flagged||x?.categories?.sexual===true));}catch(e){console.error('Automatic moderation failed:',e);return false;}}
async function moderatePostData(ref,data,days,reason){if(!data?.authorUid||!(await containsAdultContent(data,OPENAI_API_KEY.value())))return false;await ref.delete();await suspendUser(data.authorUid,days,reason);return true;}
exports.moderateAdultPost=onDocumentCreated({document:'posts/{postId}',secrets:[OPENAI_API_KEY]},async e=>{await moderatePostData(e.data.ref,e.data.data(),3,'adult_content_post');});
exports.moderateAdultComment=onDocumentCreated({document:'posts/{postId}/comments/{commentId}',secrets:[OPENAI_API_KEY]},async e=>{await moderatePostData(e.data.ref,e.data.data(),3,'adult_content_comment');});
exports.moderateAdultCommunityMessage=onDocumentCreated({document:'communities/{communityId}/messages/{messageId}',secrets:[OPENAI_API_KEY]},async e=>{const d=e.data?.data();if(!d?.senderUid||!(await containsAdultContent(d,OPENAI_API_KEY.value())))return;const ref=admin.firestore().collection('communities').doc(e.params.communityId);const c=(await ref.get()).data()||{};await e.data.ref.delete();if(c.type==='channel'){await admin.firestore().recursiveDelete(ref);await suspendUser(d.senderUid,5,'adult_content_channel');}else await suspendUser(d.senderUid,3,'adult_content_group_message');});
exports.restoreModerationSuspensions=onSchedule('every 15 minutes',async()=>{const now=admin.firestore.Timestamp.now();const s=await admin.firestore().collection('users').where('moderationSuspendedUntil','<=',now).limit(100).get();for(const doc of s.docs){try{await admin.auth().updateUser(doc.id,{disabled:false});await doc.ref.update({moderationSuspendedUntil:admin.firestore.FieldValue.delete(),moderationReason:admin.firestore.FieldValue.delete()});}catch(e){console.error(`Failed to restore ${doc.id}`,e);}}});
exports.notifyNewMessage=onDocumentCreated('conversations/{conversationId}/messages/{messageId}',async e=>{const d=e.data?.data();if(!d?.senderUid)return;const c=await admin.firestore().collection('conversations').doc(e.params.conversationId).get();const ps=c.get('participants')||[];const receiver=ps.find(uid=>uid!==d.senderUid);if(!receiver)return;const s=await admin.firestore().collection('users').doc(d.senderUid).get();const name=s.get('displayName')||s.get('phone')||'Контакт';await sendToUser(receiver,{notification:{title:name,body:String(d.text||'Новое сообщение').slice(0,120)},data:{type:'message',conversationId:e.params.conversationId,senderUid:d.senderUid}});});
exports.notifyFriendRequest=onDocumentCreated('friendRequests/{requestId}',async e=>{const d=e.data?.data();if(!d?.receiverUid||d.status!=='pending')return;const s=await admin.firestore().collection('users').doc(d.senderUid).get();const name=s.get('displayName')||s.get('phone')||'Контакт';await sendToUser(d.receiverUid,{notification:{title:'👥 Новая заявка',body:`${name} хочет добавить вас в друзья`},data:{type:'friend_request',requestId:e.params.requestId,senderUid:d.senderUid}});});
exports.notifyCommunityMessage=onDocumentCreated('communities/{communityId}/messages/{messageId}',async e=>{const d=e.data?.data();if(!d?.senderUid)return;const c=(await admin.firestore().collection('communities').doc(e.params.communityId).get()).data()||{};const members=c.members||[];const name=c.name||'Сообщество';const sender=d.senderUid;const recipients=members.filter(uid=>uid&&uid!==sender).slice(0,100);for(const uid of recipients)await sendToUser(uid,{notification:{title:(c.type==='channel'?'📢 ':'👥 ')+name,body:String(d.text||'Новое сообщение').slice(0,120)},data:{type:c.type==='channel'?'channel':'group',communityId:e.params.communityId,senderUid:sender}});});
exports.notifyIncomingCall=onDocumentCreated('calls/{callId}',async e=>{const d=e.data?.data();if(!d?.receiverUid||!d?.callerUid)return;const s=await admin.firestore().collection('users').doc(d.callerUid).get();const name=s.get('displayName')||s.get('phone')||'Контакт';const video=d.type==='video';await sendToUser(d.receiverUid,{notification:{title:video?'📹 Видеозвонок':'📞 Входящий звонок',body:`${name} звонит вам`},data:{type:'call',callId:e.params.callId,callerUid:d.callerUid,callType:d.type||'audio'},android:{priority:'high'}});});
