plugins {
    id 'com.android.application'
}

if (file('google-services.json').exists()) {
    apply plugin: 'com.google.gms.google-services'
}

android {
    namespace 'com.montakte.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.montakte.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-auth'
}
